spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    databasePlatform: org.hibernate.dialect.H2Dialect
    deferDatasourceInitialization: true
    showSql: true
    properties:
      hibernate:
        format_sql: true

config:
  test: hello world test

